run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - exportloopref
    - prealloc

linters-settings:
  gosec:
    excludes:
      - G104  # Unhandled errors (we handle them appropriately)

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment

  misspell:
    locale: US

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - unparam
